"""Media Triage Module with 3-tier smart filtering, in-memory provenance, and on-demand camera/AI extraction."""

import io
import re
import logging
from typing import Dict, Any, List, Optional
import httpx
from PIL import Image
import numpy as np
import cv2

logger = logging.getLogger(__name__)


class MediaTriage:
    """Smart triage for media assets:
    - Tier 1: URL extraction & avatar/noise filtering (skip profile pictures, UI icons, banners)
    - Tier 2: Engagement & Risk prioritization (only triage user-uploaded content)
    - Tier 3: Metadata & EXIF provenance check (detect AI software tags without heavy GPU inference)
    - Zero Disk Storage: 100% ephemeral in-memory processing.
    """

    AI_GENERATOR_TAGS = [
        "midjourney", "dall-e", "dalle", "stable diffusion", "stablediffusion",
        "bing image creator", "firefly", "adobe firefly", "generative ai",
        "imagen", "flux", "flux.1", "leonardo.ai", "novelai", "comfyui",
        "text-to-image", "image-to-image", "text-to-3d", "image-to-3d",
        "genai", "ai art", "ai generated", "generated by ai", "prompt:",
        "civitai", "chatgpt", "sora", "deepfake", "synthetic",
        "#aiart", "#midjourney", "#stablediffusion"
    ]

    AI_VIDEO_GENERATOR_TAGS = [
        "sora", "openai sora", "kling", "kling ai", "klingai", "runway", "runwayml",
        "gen-2", "gen-3", "gen3", "luma", "dream machine", "pika", "pika labs",
        "pikalabs", "hailuo", "minimax", "cogvideo", "stable video diffusion", "svd",
        "text-to-video", "image-to-video", "ai video", "ai animation", "ai generated video",
        "synthetic video", "animated with ai", "#aivideo", "#sora", "#kling", "#aishorts",
        "#runwaygen3", "#lumadreammachine"
    ]

    IGNORED_PATTERNS = [
        r"profile_images", r"default_profile", r"profile_banner", r"avatar",
        r"mini_avatar", r"favicon", r"icon", r"badge", r"emoji", r"spacer",
        r"logo_small", r"thumb_24x24", r"thumb_48x48"
    ]

    def extract_media_urls_sync(self, post_or_raw: Any, platform: str = "") -> List[str]:
        """Synchronously extract candidate media URLs while filtering out profile pics and UI clutter."""
        candidate_urls: List[str] = []

        raw_data = post_or_raw if isinstance(post_or_raw, dict) else getattr(post_or_raw, "raw_data", {}) or {}
        post_id = getattr(post_or_raw, "id", "") if hasattr(post_or_raw, "id") else ""
        plat = (platform or getattr(post_or_raw, "platform", "") or "").lower()

        # 1. Platform-Specific Extraction
        if plat == "youtube":
            clean_id = str(post_id).replace("yt_", "")
            if clean_id and not clean_id.startswith("http"):
                candidate_urls.append(f"https://img.youtube.com/vi/{clean_id}/hqdefault.jpg")

        elif plat == "x":
            photos = raw_data.get("photos", []) or []
            for ph in photos:
                url = ph.get("url") if isinstance(ph, dict) else getattr(ph, "url", None)
                if url:
                    candidate_urls.append(url)
            
            media_list = raw_data.get("media", []) or []
            if isinstance(media_list, list):
                for m in media_list:
                    if isinstance(m, dict):
                        m_url = m.get("media_url_https") or m.get("url") or m.get("preview_image_url")
                        if m_url:
                            candidate_urls.append(m_url)

        elif plat in ("instagram", "facebook"):
            for key in ("display_url", "image", "thumbnail_url", "media_url", "thumbnail"):
                val = raw_data.get(key)
                if isinstance(val, str) and val.startswith("http"):
                    candidate_urls.append(val)

        elif plat == "reddit":
            url_val = raw_data.get("url") or ""
            if any(url_val.lower().endswith(ext) for ext in (".jpg", ".jpeg", ".png", ".webp")):
                candidate_urls.append(url_val)
            thumb = raw_data.get("thumbnail")
            if isinstance(thumb, str) and thumb.startswith("http"):
                candidate_urls.append(thumb)

        # 2. Recursive search
        def walk(obj: Any):
            if isinstance(obj, dict):
                for k, v in obj.items():
                    if k.lower() in ("url", "src", "media_url", "display_url", "image_url") and isinstance(v, str):
                        if v.startswith("http") and any(ext in v.lower() for ext in (".jpg", ".jpeg", ".png", ".webp")):
                            candidate_urls.append(v)
                    walk(v)
            elif isinstance(obj, list):
                for item in obj:
                    walk(item)

        if not candidate_urls:
            walk(raw_data)

        # 3. Filter noise, avatars, duplicates
        filtered_urls: List[str] = []
        seen = set()

        for url in candidate_urls:
            url_clean = url.split("?")[0].strip()
            if url_clean in seen:
                continue

            is_noise = any(re.search(pat, url_clean, re.IGNORECASE) for pat in self.IGNORED_PATTERNS)
            if is_noise:
                continue

            lower_u = url.lower()
            if any(ext in lower_u for ext in (".jpg", ".jpeg", ".png", ".webp")) or "twimg.com/media" in lower_u or "ytimg.com/vi" in lower_u or "scontent" in lower_u:
                seen.add(url_clean)
                filtered_urls.append(url)

        return filtered_urls[:2]

    async def extract_media_urls(self, post_or_raw: Any, platform: str = "") -> List[str]:
        """Async compatibility wrapper."""
        return self.extract_media_urls_sync(post_or_raw, platform)

    def _analyze_pixel_forensics(self, img: Image.Image) -> Dict[str, Any]:
        """In-memory pixel-level forensic analysis for diffusion artifacts:
        - 2D Fast Fourier Transform (FFT) high-frequency peak density / grid artifacts
        - Gaussian noise residual kurtosis (distinguishes physical camera PRNU noise from diffusion denoising)
        - Flat-patch micro-texture variance
        """
        try:
            arr = np.array(img)
            if len(arr.shape) == 3:
                if arr.shape[2] == 4:
                    gray = cv2.cvtColor(arr, cv2.COLOR_RGBA2GRAY)
                elif arr.shape[2] == 3:
                    gray = cv2.cvtColor(arr, cv2.COLOR_RGB2GRAY)
                else:
                    gray = arr[:, :, 0]
            else:
                gray = arr

            h, w = gray.shape
            if h < 32 or w < 32:
                return {"kurtosis": 0.0, "hf_peak_density": 0.0, "flat_patch_var": 10.0}

            # 1. 2D FFT Spectral Analysis
            f = np.fft.fft2(gray)
            fshift = np.fft.fftshift(f)
            mag = np.abs(fshift)
            cy, cx = h // 2, w // 2
            y, x = np.ogrid[:h, :w]
            dist = np.sqrt((x - cx) ** 2 + (y - cy) ** 2)
            max_d = np.sqrt(cx ** 2 + cy ** 2)
            hf_mask = dist > (max_d * 0.45)

            if np.sum(hf_mask) > 0:
                mean_hf = np.mean(mag[hf_mask])
                std_hf = np.std(mag[hf_mask])
                hf_peaks = np.sum(mag[hf_mask] > (mean_hf + 3 * std_hf))
                hf_peak_density = float(hf_peaks / np.sum(hf_mask))
            else:
                hf_peak_density = 0.0

            # 2. Gaussian Noise Residual Kurtosis
            blurred = cv2.GaussianBlur(gray, (5, 5), 1.0)
            noise_res = gray.astype(float) - blurred.astype(float)
            res_std = float(np.std(noise_res))
            if res_std > 1e-4:
                kurtosis = float(np.mean(((noise_res - np.mean(noise_res)) / res_std) ** 4) - 3.0)
            else:
                kurtosis = 0.0

            # 3. Flat-patch micro-texture variance
            block_vars = []
            step = 16
            for by in range(0, min(h - step, 512), step):
                for bx in range(0, min(w - step, 512), step):
                    patch = gray[by:by + step, bx:bx + step]
                    pv = float(np.var(patch))
                    if pv < 40.0:
                        block_vars.append(pv)
            flat_patch_var = float(np.mean(block_vars)) if block_vars else 8.0

            return {
                "kurtosis": round(kurtosis, 2),
                "res_std": round(res_std, 2),
                "hf_peak_density": round(hf_peak_density, 4),
                "flat_patch_var": round(flat_patch_var, 2)
            }
        except Exception as e:
            logger.warning(f"Pixel forensics calculation error: {e}")
            return {"kurtosis": 0.0, "hf_peak_density": 0.0, "flat_patch_var": 8.0}

    async def fetch_and_analyze_metadata(
        self,
        url: str,
        post_text: str = "",
        post_id: str = ""
    ) -> Dict[str, Any]:
        """Tier 3: In-memory ephemeral metadata and pixel-level forensic inspection (Zero Disk Storage).
        Checks EXIF provenance, contextual post correlation, and frequency/noise residual signatures.
        """
        result: Dict[str, Any] = {
            "url": url,
            "has_exif": False,
            "is_ai_generated": False,
            "ai_score": 0.15,
            "verdict": "CLEAN_HUMAN_OR_COMPRESSED",
            "label": "HUMAN / NO AI DETECTED",
            "badge_color": "#38bdf8",
            "software": None,
            "camera": None,
            "dimensions": None,
            "file_size_kb": 0,
            "details": "Standard sensor noise & natural frequency spectrum. Zero synthetic AI signatures found.",
            "error": None
        }

        image_bytes: Optional[io.BytesIO] = None
        img: Optional[Image.Image] = None

        try:
            async with httpx.AsyncClient(timeout=6.0, follow_redirects=True) as client:
                # 1. Fast HEAD check: reject files > 10MB immediately
                try:
                    head = await client.head(url)
                    cl = int(head.headers.get("Content-Length", 0))
                    if cl > 10 * 1024 * 1024:
                        result["error"] = "Skipped: File too large (>10MB)"
                        result["details"] = "Image exceeds 10MB pre-check cap."
                        return result
                except Exception:
                    pass

                # 2. Ephemeral In-Memory GET
                resp = await client.get(url, headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"})
                if resp.status_code != 200:
                    result["error"] = f"HTTP {resp.status_code}"
                    return result

                content_len = len(resp.content)
                result["file_size_kb"] = round(content_len / 1024, 1)

                # 3. Parse in-memory stream
                image_bytes = io.BytesIO(resp.content)
                img = Image.open(image_bytes)
                result["dimensions"] = f"{img.width}x{img.height}"

                # 4. Extract EXIF metadata
                make_tag = ""
                model_tag = ""
                software_tag = ""
                software_match = None
                exif = img.getexif()

                if exif:
                    result["has_exif"] = True
                    software_tag = str(exif.get(305) or "").strip()   # 305 = Software
                    desc_tag = str(exif.get(270) or "").strip()       # 270 = ImageDescription
                    artist_tag = str(exif.get(315) or "").strip()     # 315 = Artist
                    make_tag = str(exif.get(271) or "").strip()       # 271 = Make (Apple, Canon)
                    model_tag = str(exif.get(272) or "").strip()     # 272 = Model (iPhone, EOS)

                    combined_exif = f"{software_tag} {desc_tag} {artist_tag}".lower()
                    for ai_tag in self.AI_GENERATOR_TAGS:
                        if ai_tag in combined_exif:
                            software_match = software_tag or ai_tag
                            break

                # 5. Contextual Post Correlation
                combined_context = f"{post_text} {url}".lower()
                context_hits = [k for k in self.AI_GENERATOR_TAGS if k in combined_context]

                # 6. In-Memory Pixel Forensic Analysis
                forensics = self._analyze_pixel_forensics(img)
                kurtosis = forensics.get("kurtosis", 0.0)
                hf_density = forensics.get("hf_peak_density", 0.0)
                flat_var = forensics.get("flat_patch_var", 8.0)

                # 7. Composite Multi-Signal Scoring
                score = 0.15
                signals = []

                if software_match:
                    score += 0.55
                    signals.append(f"EXIF tag ({software_match})")

                if context_hits:
                    score += 0.50
                    signals.append(f"Context mentions '{context_hits[0]}'")

                if kurtosis > 17.0:
                    score += 0.35
                    signals.append(f"Extreme noise residual kurtosis ({kurtosis:.1f})")
                elif kurtosis > 12.0:
                    score += 0.20
                    signals.append(f"Elevated noise residual kurtosis ({kurtosis:.1f})")

                if hf_density > 0.012 and kurtosis > 10.0:
                    score += 0.15
                    signals.append("High-frequency periodic spectral spikes")

                if flat_var < 3.5 and kurtosis > 14.0:
                    score += 0.15
                    signals.append("Unnatural synthetic surface smoothness")

                if make_tag or model_tag:
                    camera_name = f"{make_tag} {model_tag}".strip()
                    score -= 0.45
                    signals.append(f"Hardware camera capture ({camera_name})")

                score = max(0.02, min(0.98, score))
                is_ai = score >= 0.50

                # 8. Verdict & Output Formation
                if is_ai:
                    result["is_ai_generated"] = True
                    result["ai_score"] = round(score, 2)
                    tag_name = software_match or (context_hits[0] if context_hits else "Diffusion Footprint")
                    result["software"] = tag_name
                    result["verdict"] = "LIKELY_AI_GENERATED"
                    result["label"] = f"LIKELY AI GENERATED ({tag_name.upper()})"
                    result["badge_color"] = "#a855f7"
                    sig_str = "; ".join(signals) if signals else "Synthetic diffusion artifact footprint"
                    result["details"] = f"Synthetic generative footprint detected: {sig_str}. Score: {int(score * 100)}%."

                elif make_tag or model_tag:
                    camera_name = f"{make_tag} {model_tag}".strip()
                    result["camera"] = camera_name
                    result["verdict"] = "AUTHENTIC_CAMERA_PHOTO"
                    result["label"] = f"AUTHENTIC PHOTO ({camera_name})"
                    result["badge_color"] = "#00e599"
                    result["details"] = f"Hardware EXIF tags confirm physical camera capture ({camera_name}). Natural sensor noise profile."

                elif software_tag:
                    result["software"] = software_tag
                    result["verdict"] = "EDITED_OR_EXPORTED"
                    result["label"] = f"HUMAN EDITED ({software_tag})"
                    result["badge_color"] = "#38bdf8"
                    result["details"] = f"Exported or edited via {software_tag}. Normal sensor noise profile."

                else:
                    result["verdict"] = "CLEAN_HUMAN_OR_COMPRESSED"
                    result["label"] = "HUMAN / NO AI DETECTED"
                    result["badge_color"] = "#38bdf8"
                    result["details"] = "Standard sensor noise & natural frequency spectrum. Zero synthetic AI signatures found."

        except Exception as e:
            logger.warning(f"Media triage notice for {url}: {e}")
            result["error"] = str(e)
        finally:
            # 9. Immediate in-memory cleanup
            if img is not None:
                try:
                    img.close()
                except Exception:
                    pass
            if image_bytes is not None:
                try:
                    image_bytes.close()
                except Exception:
                    pass

        return result

    def extract_video_info(self, post_or_raw: Any, platform: str = "") -> Optional[Dict[str, Any]]:
        """Extract structured video metadata for YouTube Shorts, Instagram Reels, and direct video streams."""
        raw_data = post_or_raw if isinstance(post_or_raw, dict) else getattr(post_or_raw, "raw_data", {}) or {}
        post_id = str(getattr(post_or_raw, "id", "") if hasattr(post_or_raw, "id") else (raw_data.get("id") or ""))
        url = str(getattr(post_or_raw, "url", "") if hasattr(post_or_raw, "url") else (raw_data.get("url") or ""))
        plat = (platform or getattr(post_or_raw, "platform", "") or "").lower()
        text = str(getattr(post_or_raw, "text", "") if hasattr(post_or_raw, "text") else (raw_data.get("text") or ""))

        # 1. YouTube Video or YouTube Short
        if plat == "youtube" or "youtube.com" in url or "youtu.be" in url:
            video_id = raw_data.get("videoId") or ""
            if not video_id:
                clean_id = post_id.replace("yt_", "")
                if clean_id and not clean_id.startswith("http"):
                    video_id = clean_id
            if not video_id and "v=" in url:
                m = re.search(r'v=([a-zA-Z0-9_-]+)', url)
                if m:
                    video_id = m.group(1)
            if not video_id and "/shorts/" in url:
                m = re.search(r'/shorts/([a-zA-Z0-9_-]+)', url)
                if m:
                    video_id = m.group(1)

            if video_id:
                is_short = "/shorts/" in url.lower() or "#shorts" in text.lower() or "#short" in text.lower()
                return {
                    "is_video": True,
                    "video_type": "youtube_short" if is_short else "youtube_video",
                    "video_id": video_id,
                    "embed_url": f"https://www.youtube.com/embed/{video_id}",
                    "preview_url": f"https://img.youtube.com/vi/{video_id}/hqdefault.jpg",
                    "watch_url": f"https://www.youtube.com/shorts/{video_id}" if is_short else f"https://www.youtube.com/watch?v={video_id}",
                    "keyframes": [
                        f"https://img.youtube.com/vi/{video_id}/0.jpg",
                        f"https://img.youtube.com/vi/{video_id}/1.jpg",
                        f"https://img.youtube.com/vi/{video_id}/2.jpg",
                        f"https://img.youtube.com/vi/{video_id}/3.jpg"
                    ]
                }

        # 2. Instagram Reel or Video
        if plat == "instagram" or "instagram.com" in url:
            code = raw_data.get("code") or ""
            if not code and "/p/" in url:
                m = re.search(r'/p/([a-zA-Z0-9_-]+)', url)
                if m:
                    code = m.group(1)
            if not code and "/reel/" in url:
                m = re.search(r'/reel/([a-zA-Z0-9_-]+)', url)
                if m:
                    code = m.group(1)

            is_reel = "/reel/" in url.lower() or "#reels" in text.lower() or "#reel" in text.lower() or raw_data.get("is_video")
            video_stream = raw_data.get("video_url") or ""

            if is_reel or video_stream or code:
                return {
                    "is_video": True,
                    "video_type": "instagram_reel" if is_reel else "instagram_video",
                    "video_id": code or post_id,
                    "embed_url": f"https://www.instagram.com/reel/{code}/embed/" if code else "",
                    "preview_url": raw_data.get("display_url") or raw_data.get("thumbnail_url") or "",
                    "watch_url": url or (f"https://www.instagram.com/reel/{code}/" if code else ""),
                    "stream_url": video_stream,
                    "keyframes": []
                }

        # 3. Direct Video Streams on X (Twitter), Reddit, Facebook
        video_stream = ""
        for key in ("video_url", "video_stream", "stream_url"):
            val = raw_data.get(key)
            if isinstance(val, str) and val.startswith("http") and any(ext in val.lower() for ext in (".mp4", ".webm", ".m3u8")):
                video_stream = val
                break

        if video_stream:
            return {
                "is_video": True,
                "video_type": "direct_video",
                "video_id": post_id,
                "embed_url": video_stream,
                "preview_url": raw_data.get("preview_image_url") or raw_data.get("thumbnail") or "",
                "watch_url": url or video_stream,
                "stream_url": video_stream,
                "keyframes": []
            }

        return None

    async def _fetch_video_keyframes_in_ram(self, video_info: Dict[str, Any]) -> List[np.ndarray]:
        """Fetch chronological keyframes for a video ephemerally in RAM (0 disk storage)."""
        frames: List[np.ndarray] = []

        # A. YouTube Keyframes (0.jpg, 1.jpg, 2.jpg, 3.jpg)
        keyframes_urls = video_info.get("keyframes", [])
        if keyframes_urls:
            async with httpx.AsyncClient(timeout=8.0, follow_redirects=True) as client:
                for k_url in keyframes_urls:
                    try:
                        resp = await client.get(k_url)
                        if resp.status_code == 200:
                            nparr = np.frombuffer(resp.content, np.uint8)
                            img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                            if img is not None:
                                frames.append(img)
                    except Exception as e:
                        logger.debug(f"Error fetching keyframe {k_url}: {e}")

            if frames:
                return frames

        # B. Direct Video Stream or Reel Stream via OpenCV VideoCapture
        stream_url = video_info.get("stream_url") or video_info.get("watch_url")
        if stream_url and (stream_url.startswith("http://") or stream_url.startswith("https://")):
            try:
                cap = cv2.VideoCapture(stream_url)
                if cap.isOpened():
                    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
                    if total_frames > 5:
                        sample_indices = [
                            int(total_frames * 0.15),
                            int(total_frames * 0.35),
                            int(total_frames * 0.55),
                            int(total_frames * 0.75),
                            int(total_frames * 0.90)
                        ]
                        for idx in sample_indices:
                            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
                            ret, frame = cap.read()
                            if ret and frame is not None:
                                frames.append(frame)
                    cap.release()
            except Exception as e:
                logger.debug(f"Error sampling stream frames: {e}")

        # C. Fallback: Preview thumbnail as single keyframe
        preview_url = video_info.get("preview_url")
        if not frames and preview_url and preview_url.startswith("http"):
            try:
                async with httpx.AsyncClient(timeout=8.0, follow_redirects=True) as client:
                    resp = await client.get(preview_url)
                    if resp.status_code == 200:
                        nparr = np.frombuffer(resp.content, np.uint8)
                        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                        if img is not None:
                            frames.append(img)
            except Exception:
                pass

        return frames

    def _analyze_video_temporal_and_spatial(
        self,
        keyframes: List[np.ndarray],
        post_text: str = "",
        video_title: str = ""
    ) -> Dict[str, Any]:
        """Perform temporal motion flow variance and multi-frame spatial forensics across keyframes."""
        if not keyframes:
            return {
                "verdict": "UNKNOWN",
                "score": 0.0,
                "label": "UNABLE TO ANALYZE VIDEO",
                "badge_color": "#9ca3af",
                "details": "Could not extract video keyframes from stream."
            }

        # 1. Temporal Motion Flow (Optical Flow) between consecutive frames
        flow_variances: List[float] = []
        frame_diffs: List[float] = []

        for i in range(len(keyframes) - 1):
            try:
                f1 = cv2.resize(keyframes[i], (360, 240))
                f2 = cv2.resize(keyframes[i + 1], (360, 240))
                g1 = cv2.cvtColor(f1, cv2.COLOR_BGR2GRAY)
                g2 = cv2.cvtColor(f2, cv2.COLOR_BGR2GRAY)

                flow = cv2.calcOpticalFlowFarneback(g1, g2, None, 0.5, 3, 15, 3, 5, 1.2, 0)
                mag, _ = cv2.cartToPolar(flow[..., 0], flow[..., 1])
                flow_variances.append(float(np.var(mag)))

                diff = cv2.absdiff(g1, g2)
                frame_diffs.append(float(np.mean(diff)))
            except Exception as e:
                logger.debug(f"Optical flow calculation error: {e}")

        avg_flow_var = float(np.mean(flow_variances)) if flow_variances else 0.0
        avg_diff = float(np.mean(frame_diffs)) if frame_diffs else 0.0

        # 2. Multi-Frame Spatial Forensics (Kurtosis & FFT across keyframes)
        kurtosis_values: List[float] = []
        fft_peak_densities: List[float] = []
        flat_patch_vars: List[float] = []

        for frame in keyframes:
            try:
                rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                pil_img = Image.fromarray(rgb)
                forensics = self._analyze_pixel_forensics(pil_img)
                kurtosis_values.append(forensics.get("kurtosis", 0.0))
                fft_peak_densities.append(forensics.get("hf_peak_density", 0.0))
                flat_patch_vars.append(forensics.get("flat_patch_var", 8.0))
            except Exception as e:
                logger.debug(f"Keyframe forensic error: {e}")

        avg_kurtosis = float(np.mean(kurtosis_values)) if kurtosis_values else 0.0
        avg_fft = float(np.mean(fft_peak_densities)) if fft_peak_densities else 0.0
        avg_flat_var = float(np.mean(flat_patch_vars)) if flat_patch_vars else 8.0

        # 3. Contextual Video Tags
        combined_text = f"{video_title} {post_text}".lower()
        tag_hits = [t for t in self.AI_VIDEO_GENERATOR_TAGS if t in combined_text]

        # 4. Multi-Signal Composite Scoring
        score = 0.10
        signals: List[str] = []

        if tag_hits:
            score += 0.50
            signals.append(f"Context mentions '{tag_hits[0]}'")

        if avg_kurtosis > 16.0:
            score += 0.35
            signals.append(f"Extreme diffusion noise kurtosis ({avg_kurtosis:.1f})")
        elif avg_kurtosis > 12.0:
            score += 0.20
            signals.append(f"Elevated noise kurtosis ({avg_kurtosis:.1f})")

        if avg_fft > 0.012 and avg_kurtosis > 10.0:
            score += 0.15
            signals.append("High-frequency periodic spectral lattice spikes")

        if avg_flat_var < 3.5 and avg_kurtosis > 14.0:
            score += 0.15
            signals.append("Unnatural synthetic surface smoothness")

        if avg_kurtosis <= 7.0 and not tag_hits:
            score -= 0.25
            signals.append("Physical camera sensor PRNU noise profile")

        score = max(0.02, min(0.98, score))
        is_ai = score >= 0.50

        # 5. Verdict Formation
        if is_ai:
            tag_label = tag_hits[0].upper() if tag_hits else "SORA / KLING / DIFFUSION"
            sig_str = "; ".join(signals) if signals else "Synthetic generative video artifacts detected"
            return {
                "is_ai_generated": True,
                "is_ai_video": True,
                "score": round(score, 2),
                "ai_score": round(score, 2),
                "verdict": "LIKELY_AI_VIDEO",
                "label": f"LIKELY AI VIDEO ({tag_label})",
                "badge_color": "#a855f7",
                "details": f"Synthetic generative video detected: {sig_str}.",
                "keyframes_analyzed": len(keyframes),
                "avg_kurtosis": round(avg_kurtosis, 2),
                "temporal_flow_variance": round(avg_flow_var, 2)
            }
        else:
            return {
                "is_ai_generated": False,
                "is_ai_video": False,
                "score": round(score, 2),
                "ai_score": round(score, 2),
                "verdict": "NATURAL_CAMERA_VIDEO",
                "label": "NATURAL CAMERA VIDEO",
                "badge_color": "#00e599",
                "details": f"Natural optical flow motion ({avg_flow_var:.1f}) and physical sensor noise profile ({avg_kurtosis:.1f}). Zero synthetic video artifacts.",
                "keyframes_analyzed": len(keyframes),
                "avg_kurtosis": round(avg_kurtosis, 2),
                "temporal_flow_variance": round(avg_flow_var, 2)
            }

    async def verify_video(
        self,
        video_url: str,
        post_id: str = "",
        platform: str = "",
        post_text: str = "",
        raw_data: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Perform on-demand in-memory temporal & spatial forensic verification on a video asset."""
        import time
        start_t = time.time()

        dummy_post = {
            "id": post_id,
            "url": video_url,
            "platform": platform,
            "text": post_text,
            "raw_data": raw_data or {}
        }
        video_info = self.extract_video_info(dummy_post, platform=platform)
        if not video_info:
            video_info = {
                "is_video": True,
                "video_type": "direct_video",
                "video_id": post_id or "vid_unknown",
                "watch_url": video_url,
                "preview_url": video_url if any(video_url.endswith(ext) for ext in (".jpg", ".png", ".webp")) else "",
                "stream_url": video_url if any(video_url.endswith(ext) for ext in (".mp4", ".webm", ".m3u8")) else "",
                "keyframes": []
            }

        # 1. Fetch keyframes in RAM
        keyframes = await self._fetch_video_keyframes_in_ram(video_info)

        # 2. Analyze temporal coherence and spatial forensics
        analysis = self._analyze_video_temporal_and_spatial(
            keyframes=keyframes,
            post_text=post_text,
            video_title=post_text.split("\n")[0][:75]
        )

        analysis["elapsed_seconds"] = round(time.time() - start_t, 2)
        analysis["video_type"] = video_info.get("video_type", "video")

        return {
            "success": True,
            "result": analysis,
            "video_info": video_info
        }
